### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by codec-abc** [gluon-lang/try_gluon#10]
Hi,

The web server [http://52.28.135.57:8080/](http://52.28.135.57:8080/) appears to be down.

**Comment by Marwes** [comment]
Thanks for reporting. Not sure why I went down (log shows nothing strange). Re-deploying it now.

**Comment by Marwes** [comment]
Oh right, I may have crashed it by accident over Christmas and then I couldn't re-deploy it since I didn't have access from my laptop. Seems to be some lingering bugs from the update. Should be fixable in a bit.

**Comment by Marwes** [comment]
It is up and working now! Thanks again for reminding me!

**Comment by codec-abc** [comment]
It is broken again  :(

**Comment by Marwes** [comment]
Huh, http://gluon-lang.org/try/ works though (trailing `/`)

**Comment by codec-abc** [comment]
Well, maybe you can put a redirect from [http://gluon-lang.org/try](http://gluon-lang.org/try/] to [http://gluon-lang.org/try/ ](http://gluon-lang.org/try/) and it will fix the issue maybe?

**Comment by Marwes** [comment]
Looking into it, must have messed up routing somehow :)
